# Generated by Django 5.1.4 on 2025-01-12 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
        ('store', '0004_item_code_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='etching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_576', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('range_720_1728', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('range_1872_2880', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('range_3024_4032', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('range_4608', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.color')),
                ('etching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.etching')),
                ('thickness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.thickness')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.text')),
            ],
        ),
    ]
