# Generated by Django 5.1.4 on 2025-01-12 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_color_etching_text_psi'),
        ('store', '0004_item_code_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psi',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', unique=True),
        ),
        migrations.AlterField(
            model_name='psi',
            name='thickness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.thickness', unique=True),
        ),
    ]
