# Generated by Django 5.1.4 on 2025-01-12 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_alter_psi_category_alter_psi_thickness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psi',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.color', unique=True),
        ),
        migrations.AlterField(
            model_name='psi',
            name='etching',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.etching', unique=True),
        ),
        migrations.AlterField(
            model_name='psi',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.text', unique=True),
        ),
    ]
