# Generated by Django 5.1.4 on 2025-01-12 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_alter_psi_category_alter_psi_color_alter_psi_etching_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='etching',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='description',
            new_name='name',
        ),
    ]
