# Generated by Django 5.1.4 on 2025-01-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0006_rename_type_color_name_rename_type_etching_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
