# Generated by Django 5.1.4 on 2025-01-19 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0007_alter_text_name'),
        ('store', '0004_item_code_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='text',
            new_name='text_matter',
        ),
        migrations.RenameField(
            model_name='psi',
            old_name='text',
            new_name='text_matter',
        ),
        migrations.AlterUniqueTogether(
            name='psi',
            unique_together={('category', 'thickness', 'etching', 'color', 'text_matter')},
        ),
    ]
