# Generated by Django 5.1.4 on 2025-01-19 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0008_rename_text_text_matter_rename_text_psi_text_matter_and_more'),
        ('store', '0004_item_code_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_child',
            name='color_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.color'),
        ),
        migrations.AlterField(
            model_name='order_child',
            name='etching',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.etching'),
        ),
        migrations.AlterField(
            model_name='order_child',
            name='text_matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.text_matter'),
        ),
        migrations.AlterField(
            model_name='order_child',
            name='thickness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.thickness'),
        ),
    ]
