# Generated by Django 5.1.4 on 2025-01-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0009_alter_order_child_color_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='edit_explanation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_declimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
