# Generated by Django 5.1.4 on 2025-01-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0010_order_edit_explanation_order_is_declimed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='edit_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
