# Generated by Django 5.1.4 on 2025-01-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0011_alter_order_edit_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
