# Generated by Django 5.1.4 on 2025-01-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0012_order_is_converted'),
    ]

    operations = [
        migrations.CreateModel(
            name='process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
