# Generated by Django 5.1.4 on 2025-01-28 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0013_process'),
        ('store', '0004_item_code_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='psi',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='psi',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotation.process'),
        ),
        migrations.AlterUniqueTogether(
            name='psi',
            unique_together={('category', 'thickness', 'etching', 'color', 'text_matter', 'process')},
        ),
    ]
