# Generated by Django 5.1.4 on 2025-02-05 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0017_alter_sales_customer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='edit_explanation',
        ),
        migrations.AlterField(
            model_name='order',
            name='industry',
            field=models.CharField(choices=[('automotive', 'automotive'), ('auto_ancillary', 'auto ancillary'), ('sugar', 'sugar'), ('project', 'project'), ('domestic_appliance', 'domestic appliance'), ('process_equipmen', 'process equipmen'), ('petro_chemica', 'petro chemica'), ('food_equipmen', 'food equipmen'), ('medical_device_equipement', 'medical device & equipement'), ('defence', 'defence'), ('aviation_aero_space', 'aviation & aero space'), ('elevator', 'elevator'), ('electricals', 'electricals'), ('electronics', 'electronics'), ('filteration', 'filteration'), ('other', 'other')], max_length=100),
        ),
        migrations.CreateModel(
            name='edit_reasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('nameplate', 'nameplate'), ('front_pannel', 'front pannel'), ('nameplate_with_qr_code', 'nameplate with qr code'), ('project_based_cable_tags', 'project based cable tags'), ('schematic_drg', 'schematic drg'), ('thin_shim_and_spacer', 'thin shim & spacer'), ('proto_type_stator_and_rotar_lamination', 'proto type stator & rotar lamination'), ('regular_thin_mesh', 'regular thin mesh'), ('customized_mesh', 'customized mesh'), ('encoder_disc', 'encoder disc'), ('aperture_and_pin_holes', 'aperture & pin holes'), ('texturing', 'texturing'), ('speaker_grill', 'speaker grill'), ('contact_connector_and_terminals', 'contact , connector & terminals'), ('valve_and_compressor_plate', 'valve & compressor plate'), ('diaphragm', 'diaphragm'), ('emi_rfi_shielding', 'emi / rfi shielding'), ('filteration', 'filteration'), ('battery_contact', 'battery contact'), ('antenna_tele_communication', 'antenna tele communication'), ('bipolar_plate_pem', 'bipolar plate pem'), ('flat_spring_u_spring_v_spring', 'flat spring, u spring, v spring'), ('metal_business_card_with_nfc_chip', 'metal business card with nfc chip'), ('metal_business_card_without_chip', 'metal business card without chip'), ('book_mark_and_product_model', 'book mark & product model'), ('designer_stainless_steel_sheet', 'designer stainless steel sheet'), ('designer_stainless_steel_sheet_with_elevator_cabinet', 'designer stainless steel sheet with elevator cabinet'), ('designer_stainless_steel_sheet_with_elevator_cabinet_roof_and_bottom', 'designer stainless steel sheet with elevator cabinet, roof & bottom'), ('other', 'other')], max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.order')),
            ],
        ),
    ]
