# Generated by Django 5.1.4 on 2025-02-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0018_remove_order_edit_explanation_alter_order_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='RRA1', editable=False, max_length=20),
            preserve_default=False,
        ),
    ]
