# Generated by Django 5.1.4 on 2025-02-16 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0019_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit_reasons',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_ref', to='quotation.order'),
        ),
    ]
