# Generated by Django 4.1.5 on 2023-09-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_reception',
            field=models.BooleanField(default=True),
        ),
    ]
