# Generated by Django 4.1.5 on 2023-09-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_reception'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_buyer',
            new_name='is_accounts',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_supplier',
            new_name='is_designer',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_reception',
            field=models.BooleanField(default=False),
        ),
    ]
