# Generated by Django 4.1.5 on 2023-09-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_is_buyer_user_is_accounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_cutter',
            field=models.BooleanField(default=False),
        ),
    ]
