# Generated by Django 4.1.5 on 2024-04-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_cutter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_salesman',
            field=models.BooleanField(default=False),
        ),
    ]
