# Generated by Django 5.1.4 on 2025-08-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_salesman'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_planner',
            field=models.BooleanField(default=False),
        ),
    ]
