# Generated by Django 5.1.4 on 2025-08-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_planner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_executor',
            field=models.BooleanField(default=False),
        ),
    ]
