# Generated by Django 5.1.4 on 2025-09-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_order_booker',
            field=models.BooleanField(default=False),
        ),
    ]
