# Generated by Django 4.1.5 on 2023-07-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='godown',
        ),
    ]
