# Generated by Django 4.1.5 on 2023-07-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_godown_product_shelf_remove_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='piece',
        ),
        migrations.AddField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(default=1, upload_to='static/qrcode/'),
            preserve_default=False,
        ),
    ]
