# Generated by Django 4.1.5 on 2024-12-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_inward_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_code',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
