# Generated by Django 5.1.4 on 2025-04-17 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_item_code_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetCut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_start', models.FloatField()),
                ('y_start', models.FloatField()),
                ('x_end', models.FloatField()),
                ('y_end', models.FloatField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product_qr')),
            ],
        ),
    ]
