# Generated by Django 5.1.4 on 2025-04-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_sheetcut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheetcut',
            name='label',
        ),
        migrations.RemoveField(
            model_name='sheetcut',
            name='x_end',
        ),
        migrations.RemoveField(
            model_name='sheetcut',
            name='x_start',
        ),
        migrations.RemoveField(
            model_name='sheetcut',
            name='y_end',
        ),
        migrations.RemoveField(
            model_name='sheetcut',
            name='y_start',
        ),
        migrations.AddField(
            model_name='sheetcut',
            name='data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
