# Generated by Django 5.1.4 on 2025-08-06 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_sheetcut_label_remove_sheetcut_x_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_code',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
    ]
