# Generated by Django 4.1.5 on 2023-07-30 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_delete_product_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.godown'),
        ),
        migrations.CreateModel(
            name='product_qr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='static/qrcode/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_material_re', to='store.product')),
                ('shelf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.godown')),
            ],
        ),
    ]
