# Generated by Django 4.1.5 on 2023-07-30 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_shelf_product_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_qr',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_material_re', to='store.product'),
        ),
    ]
