# Generated by Django 4.1.5 on 2023-08-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_employee_product_qr_date_of_pur_product_qr_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_qr',
            name='date_of_pur',
            field=models.DateField(blank=True, null=True),
        ),
    ]
