# Generated by Django 4.1.5 on 2023-08-24 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_qr_date_of_pur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_qr',
            name='date_of_pur',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
