# Generated by Django 4.1.5 on 2023-08-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_product_qr_date_of_pur'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_qr',
            name='is_fix',
            field=models.BooleanField(default=False),
        ),
    ]
