# Generated by Django 4.1.5 on 2023-08-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_qr_is_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_qr',
            name='moved_to_scratch',
            field=models.BooleanField(default=False),
        ),
    ]
