# Generated by Django 4.1.5 on 2023-08-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_qr_moved_to_scratch'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_qr',
            name='moved_to_left_over',
            field=models.BooleanField(default=False),
        ),
    ]
