# Generated by Django 4.1.5 on 2023-08-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_product_qr_moved_to_left_over'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
            ],
        ),
    ]
