# Generated by Django 4.1.5 on 2023-08-31 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_item_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='category',
        ),
        migrations.RemoveField(
            model_name='size',
            name='category',
        ),
        migrations.RemoveField(
            model_name='thickness',
            name='category',
        ),
    ]
