# Generated by Django 4.1.5 on 2023-09-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_grade_category_remove_size_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cutter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('mobile_no', models.IntegerField()),
            ],
        ),
    ]
