# Generated by Django 4.1.5 on 2023-09-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_cutter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_qr',
            name='linked_sheet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
