# Generated by Django 4.1.5 on 2023-09-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_product_qr_linked_sheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_qr',
            name='linked_sheet',
        ),
    ]
