# Generated by Django 4.1.5 on 2023-09-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_size_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_qr',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='media/uploads/'),
        ),
    ]
