# Generated by Django 4.1.5 on 2023-09-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_product_qr_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.FloatField(default=0),
        ),
    ]
