# Generated by Django 4.1.5 on 2023-09-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_product_qr_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_qr',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
