# Generated by Django 4.1.5 on 2023-09-15 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_product_qr_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='product_qr_shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product_qr')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shelf')),
            ],
        ),
    ]
