# Generated by Django 4.1.5 on 2023-09-15 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_shelf_product_qr_shelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_qr_shelf',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.shelf'),
        ),
    ]
