# Generated by Django 4.1.5 on 2023-09-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_product_qr_shelf_shelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
