# Generated by Django 4.1.5 on 2023-09-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_shelf_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_qr',
            name='finish',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
