# Generated by Django 4.1.5 on 2023-09-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_product_qr_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_qr',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
