# Generated by Django 4.1.5 on 2023-09-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_remove_product_qr_is_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='mm1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='size',
            name='mm2',
            field=models.FloatField(default=0),
        ),
    ]
