# Generated by Django 4.1.5 on 2023-10-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_size_mm1_size_mm2'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='sdsd', max_length=120),
            preserve_default=False,
        ),
    ]
