# Generated by Django 4.1.5 on 2024-01-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_alter_product_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_qr',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
