# Generated by Django 5.1.4 on 2025-08-14 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0007_item_code_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DC_date', models.DateField()),
                ('description', models.CharField(max_length=50)),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('rra_invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('hold', 'Hold'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to='store.customer')),
                ('employee_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_employee', to='store.employee')),
            ],
        ),
    ]
