# Generated by Django 5.1.4 on 2025-08-14 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0001_initial'),
        ('store', '0007_item_code_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_matarial_production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_quantity', models.IntegerField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('barcode_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('main_label_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=50, null=True)),
                ('item_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_prod_item_code', to='store.item_code')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_production_n', to='order_booking.order_booking')),
            ],
        ),
    ]
