# Generated by Django 5.1.4 on 2025-08-14 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0002_order_matarial_production'),
        ('store', '0007_item_code_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_booking',
            name='completed',
        ),
        migrations.AddField(
            model_name='order_booking',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_booking',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('po_date', 'On PO Date')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order_booking',
            name='drawings',
            field=models.FileField(blank=True, null=True, upload_to='media/project_drawings/'),
        ),
        migrations.AddField(
            model_name='order_booking',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_booking',
            name='order_type',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('repeated', 'Repeated')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order_booking',
            name='thickness',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.thickness'),
            preserve_default=False,
        ),
    ]
