# Generated by Django 5.1.4 on 2025-08-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0003_remove_order_booking_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_booking',
            name='drawing_film_expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_booking',
            name='is_drawing_avaiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_booking',
            name='is_flim_avaiable',
            field=models.BooleanField(default=False),
        ),
    ]
