# Generated by Django 5.1.4 on 2025-08-16 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0004_order_booking_drawing_film_expected_date_and_more'),
        ('store', '0007_item_code_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_sheet_requiremnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='store.product')),
            ],
        ),
    ]
