# Generated by Django 5.1.4 on 2025-08-16 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0005_order_sheet_requiremnt'),
        ('store', '0007_item_code_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_sheet_requiremnt',
            old_name='length',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='order_sheet_requiremnt',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order_sheet_requiremnt',
            name='width',
        ),
        migrations.AddField(
            model_name='order_sheet_requiremnt',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_sheet_requiremnt',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_sheet_requiremnt',
            name='thickness',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.thickness'),
            preserve_default=False,
        ),
    ]
