# Generated by Django 5.1.4 on 2025-08-16 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0006_rename_length_order_sheet_requiremnt_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_sheet_requiremnt',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_requirements', to='order_booking.order_booking'),
            preserve_default=False,
        ),
    ]
