# Generated by Django 5.1.4 on 2025-08-16 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0007_order_sheet_requiremnt_order'),
        ('store', '0007_item_code_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='production_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('stage', models.CharField(choices=[('not_started', 'Not Started'), ('cutting', 'Cutting'), ('welding', 'Welding'), ('assembly', 'Assembly'), ('painting', 'Painting'), ('completed', 'Completed')], default='not_started', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_production', to='order_booking.order_booking')),
            ],
        ),
    ]
