# Generated by Django 5.1.4 on 2025-08-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0008_production_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_booking',
            old_name='order_id',
            new_name='purchase_no',
        ),
        migrations.RemoveField(
            model_name='order_booking',
            name='DC_date',
        ),
        migrations.RemoveField(
            model_name='order_booking',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order_booking',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='order_booking',
            name='rra_invoice_no',
        ),
        migrations.AddField(
            model_name='order_booking',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order_booking',
            name='drawing_film_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_booking',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('hold', 'Hold')], default='pending', max_length=10, null=True),
        ),
    ]
