# Generated by Django 5.1.4 on 2025-08-20 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0009_rename_order_id_order_booking_purchase_no_and_more'),
        ('store', '0007_item_code_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_booking',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='order_booking',
            name='thickness',
        ),
        migrations.AddField(
            model_name='order_matarial_production',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_matarial_production',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_matarial_production',
            name='thickness',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.thickness'),
            preserve_default=False,
        ),
    ]
