# Generated by Django 5.1.4 on 2025-08-20 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0010_remove_order_booking_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_booking',
            old_name='purchase_no',
            new_name='order_id',
        ),
    ]
