# Generated by Django 5.1.4 on 2025-08-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0011_rename_purchase_no_order_booking_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_matarial_production',
            name='barcode_count',
        ),
        migrations.RemoveField(
            model_name='order_matarial_production',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='order_matarial_production',
            name='main_label_count',
        ),
        migrations.AddField(
            model_name='order_matarial_production',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='order_sheet_requiremnt',
        ),
    ]
