# Generated by Django 5.1.4 on 2025-08-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0012_remove_order_matarial_production_barcode_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production_orders',
            name='stage',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('cutting', 'Cutting'), ('welding', 'Welding'), ('assembly', 'Assembly'), ('painting', 'Painting'), ('', 'Completed')], default='not_started', max_length=50),
        ),
    ]
