# Generated by Django 5.1.4 on 2025-08-21 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0013_alter_production_orders_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_booking',
            old_name='drawing_film_completion_date',
            new_name='drawing_expected_delivery_date',
        ),
        migrations.RenameField(
            model_name='order_booking',
            old_name='drawing_film_expected_date',
            new_name='expected_film_delivery_date',
        ),
    ]
