# Generated by Django 5.1.4 on 2025-08-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0014_rename_drawing_film_completion_date_order_booking_drawing_expected_delivery_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_booking',
            old_name='drawing_expected_delivery_date',
            new_name='design_completion_expected_date',
        ),
    ]
