# Generated by Django 5.1.4 on 2025-08-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0015_rename_drawing_expected_delivery_date_order_booking_design_completion_expected_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_booking',
            name='status',
        ),
        migrations.AlterField(
            model_name='production_orders',
            name='stage',
            field=models.CharField(choices=[('on_hold', 'On Hold'), ('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('cutting', 'Cutting'), ('welding', 'Welding'), ('assembly', 'Assembly'), ('painting', 'Painting')], default='not_started', max_length=50),
        ),
    ]
