# Generated by Django 5.1.4 on 2025-08-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0016_remove_order_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_booking',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('hold', 'Hold'), ('completed', 'Completed')], default='pending', max_length=10, null=True),
        ),
    ]
