# Generated by Django 5.1.4 on 2025-08-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0017_order_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production_orders',
            name='stage',
            field=models.CharField(choices=[('hold', 'Hold'), ('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('cutting', 'Cutting'), ('welding', 'Welding'), ('assembly', 'Assembly'), ('painting', 'Painting')], default='not_started', max_length=50),
        ),
    ]
