# Generated by Django 5.1.4 on 2025-08-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0018_alter_production_orders_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_orders',
            name='hold_reason',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('repeated', 'Repeated')], max_length=10, null=True),
        ),
    ]
