# Generated by Django 5.1.4 on 2025-08-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0020_alter_production_orders_stage'),
        ('store', '0007_item_code_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production_orders',
            name='assigned_employee',
        ),
        migrations.AddField(
            model_name='production_orders',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, related_name='production_orders', to='store.cutter'),
        ),
    ]
