# Generated by Django 5.1.4 on 2025-08-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0021_remove_production_orders_assigned_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production_orders',
            name='hold_reason',
            field=models.CharField(blank=True, choices=[('Client Delay', 'Client Delay'), ('Material Shortage', 'Material Shortage'), ('Technical Issue', 'Technical Issue'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
