# Generated by Django 5.1.4 on 2025-08-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0022_alter_production_orders_hold_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_booking',
            name='drawings',
        ),
        migrations.AddField(
            model_name='order_matarial_production',
            name='drawings',
            field=models.FileField(blank=True, null=True, upload_to='media/project_drawings/'),
        ),
        migrations.AlterField(
            model_name='order_booking',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('planning', 'Planning'), ('hold', 'Hold'), ('completed', 'Completed')], default='pending', max_length=10, null=True),
        ),
    ]
