# Generated by Django 5.1.4 on 2025-08-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0023_remove_order_booking_drawings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_booking',
            name='design_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
