# Generated by Django 5.1.4 on 2025-08-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0024_order_booking_design_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_booking',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('planning', 'Planning'), ('in_progress', 'In Progress'), ('hold', 'Hold'), ('completed', 'Completed')], default='pending', max_length=15, null=True),
        ),
    ]
