# Generated by Django 5.1.4 on 2025-09-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0025_alter_order_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production_orders',
            name='hold_reason',
            field=models.CharField(blank=True, choices=[('material_not_available', 'Required material not available'), ('unclear_drawing', 'Drawing provided is unclear or incomplete'), ('consumables_out_of_stock', 'Consumables currently out of stock'), ('power_outage', 'Execution delayed due to power outage'), ('manpower_shortage', 'Insufficient manpower to proceed'), ('other', 'Other')], max_length=40, null=True),
        ),
    ]
