# Generated by Django 5.1.4 on 2025-09-07 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0026_alter_production_orders_hold_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production_orders',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_production', to='order_booking.order_booking'),
        ),
    ]
