# Generated by Django 5.1.4 on 2025-09-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0027_alter_production_orders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_booking',
            name='total_sqinch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
