# Generated by Django 5.1.4 on 2025-09-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0028_order_booking_total_sqinch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_booking',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('active', 'Active'), ('planning', 'Planning'), ('in_progress', 'In Progress'), ('hold', 'Hold'), ('completed', 'Completed')], default='active', max_length=15, null=True),
        ),
    ]
