# Generated by Django 5.1.4 on 2025-09-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0029_alter_order_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_booking',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='production_orders',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
