# Generated by Django 5.1.4 on 2025-12-03 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0030_order_booking_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_matarial_production',
            name='drawings',
        ),
        migrations.CreateModel(
            name='order_matarial_production_drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/project_drawings/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='order_booking.order_matarial_production')),
            ],
        ),
    ]
