# Generated by Django 4.1.5 on 2023-07-28 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_category_alter_product_grade_and_more'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('quantity2', models.IntegerField()),
                ('category1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssdcddc', to='store.category')),
                ('category2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('grade1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edwd', to='store.grade')),
                ('grade2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdsdfdedcdsdsdsdgf', to='store.grade')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.project')),
                ('size1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdsdsdsdgf', to='store.size')),
                ('size2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdsdsdsdxcfsdgf', to='store.size')),
                ('thickness1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdsddwsdsdsdgf', to='store.thickness')),
                ('thickness2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdsefdsdsdgf', to='store.thickness')),
            ],
        ),
        migrations.DeleteModel(
            name='inward',
        ),
    ]
