# Generated by Django 4.1.5 on 2024-05-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_order_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_customer',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
