# Generated by Django 4.1.5 on 2023-07-28 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_qr_code_remove_product_shelf_and_more'),
        ('transactions', '0002_project_material_delete_inward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_material',
            name='category1',
        ),
        migrations.RemoveField(
            model_name='project_material',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='project_material',
            name='grade1',
        ),
        migrations.RemoveField(
            model_name='project_material',
            name='grade2',
        ),
        migrations.RemoveField(
            model_name='project_material',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='project_material',
            name='quantity2',
        ),
        migrations.RemoveField(
            model_name='project_material',
            name='size1',
        ),
        migrations.RemoveField(
            model_name='project_material',
            name='size2',
        ),
        migrations.RemoveField(
            model_name='project_material',
            name='thickness1',
        ),
        migrations.RemoveField(
            model_name='project_material',
            name='thickness2',
        ),
        migrations.AddField(
            model_name='project_material',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
    ]
