# Generated by Django 4.1.5 on 2023-07-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_project_material_category1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_material',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
