# Generated by Django 4.1.5 on 2024-06-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_sales_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_child',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_child',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
