# Generated by Django 4.1.5 on 2024-06-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_order_child_length_order_child_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_child',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
