# Generated by Django 4.1.5 on 2023-07-28 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_qr_code_remove_product_shelf_and_more'),
        ('transactions', '0004_project_material_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_material',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.product'),
        ),
    ]
