# Generated by Django 4.1.5 on 2023-07-28 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_qr_code_remove_product_shelf_and_more'),
        ('transactions', '0005_alter_project_material_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_material',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_re', to='store.product'),
        ),
    ]
