# Generated by Django 4.1.5 on 2024-07-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_order_child_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='credit_limit',
        ),
        migrations.AddField(
            model_name='sales_customer',
            name='credit_limit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_child',
            name='flim_charges',
            field=models.CharField(choices=[('inclusive', 'inclusive'), ('sqinch', 'sqinch'), ('no_flim_charges', 'no_flim_charges')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order_child',
            name='sample',
            field=models.CharField(choices=[('Free_in_case_confirm_Order', 'Free_in_case_confirm_Order'), ('Extra_Charges_Rs', 'Extra_Charges_Rs'), ('no_charges', 'no_charges')], max_length=50),
        ),
    ]
