# Generated by Django 4.1.5 on 2024-07-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_remove_order_credit_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sudden_rise',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100),
        ),
    ]
