# Generated by Django 4.1.5 on 2024-08-01 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_order_sudden_rise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_child',
            name='min_font_height',
        ),
    ]
