# Generated by Django 4.1.5 on 2024-08-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_remove_order_child_min_font_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_inward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsdvvsdcx', to='transactions.project')),
            ],
        ),
    ]
