# Generated by Django 4.1.5 on 2024-08-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_project_inward'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_inward',
            name='title',
            field=models.CharField(default='dsdsd', max_length=50),
            preserve_default=False,
        ),
    ]
