# Generated by Django 4.1.5 on 2023-07-30 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_project_matarial_qr_delete_product_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_matarial_qr',
            name='project_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_material_re', to='transactions.project_material'),
        ),
    ]
