# Generated by Django 4.1.5 on 2023-08-05 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_qr_product'),
        ('transactions', '0011_alter_project_matarial_qr_project_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_matarial_qr',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='project_matarial_qr',
            name='product_qr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product_qr'),
        ),
    ]
