# Generated by Django 4.1.5 on 2024-08-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_project_inward_invoice_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_inward',
            name='title',
        ),
        migrations.RemoveField(
            model_name='project_outward',
            name='title',
        ),
    ]
