# Generated by Django 4.1.5 on 2023-08-18 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_project_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='material_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_size', models.CharField(max_length=50)),
                ('used_size', models.CharField(max_length=50)),
                ('left_size', models.CharField(max_length=50)),
                ('project_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fdthfh', to='transactions.project_material')),
            ],
        ),
    ]
