# Generated by Django 4.1.5 on 2024-08-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_remove_project_inward_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_inward',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='project_outward',
            name='invoice_no',
        ),
    ]
