# Generated by Django 4.1.5 on 2023-08-18 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_qr_product'),
        ('transactions', '0014_material_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material_history',
            name='project_material',
        ),
        migrations.AddField(
            model_name='material_history',
            name='product_qr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fdthfh', to='store.product_qr'),
            preserve_default=False,
        ),
    ]
