# Generated by Django 4.1.5 on 2023-08-22 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_employee_product_qr_date_of_pur_product_qr_supplier'),
        ('transactions', '0015_remove_material_history_project_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dsscsdcs', to='store.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.CharField(max_length=50),
        ),
    ]
