# Generated by Django 4.1.5 on 2023-08-23 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_employee_product_qr_date_of_pur_product_qr_supplier'),
        ('transactions', '0016_project_employee_alter_project_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='godown',
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
