# Generated by Django 4.1.5 on 2024-08-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_project_matarial_production_production_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_matarial_production',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
