# Generated by Django 4.1.5 on 2023-08-23 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_employee_product_qr_date_of_pur_product_qr_supplier'),
        ('transactions', '0018_left_over_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='scratch_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product_qr')),
            ],
        ),
    ]
