# Generated by Django 4.1.5 on 2024-09-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_remove_project_inward_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_inward',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='project_outward',
            name='amount',
        ),
    ]
