# Generated by Django 4.1.5 on 2023-08-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_scratch_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='left_over_stock',
            name='quantity',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scratch_stock',
            name='quantity',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
