# Generated by Django 4.1.5 on 2024-09-02 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_remove_project_inward_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_matarial_production',
            name='production_amount',
        ),
    ]
