# Generated by Django 4.1.5 on 2024-09-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_remove_project_matarial_production_production_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
    ]
