# Generated by Django 4.1.5 on 2023-08-24 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_qr_moved_to_scratch'),
        ('transactions', '0022_remove_project_employee_project_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='left_over_stock',
            name='product',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
    ]
