# Generated by Django 4.1.5 on 2024-09-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_copy_id_to_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('hold', 'Hold'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
