# Generated by Django 4.1.5 on 2023-08-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_left_over_stock_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='left_over_stock',
            name='product_qr',
        ),
    ]
