# Generated by Django 4.1.5 on 2023-08-24 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_qr_moved_to_scratch'),
        ('transactions', '0024_remove_left_over_stock_product_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scratch_stock',
            name='product_qr',
        ),
        migrations.AddField(
            model_name='scratch_stock',
            name='product',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
    ]
