# Generated by Django 4.1.5 on 2024-09-04 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_working_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('rfid_value', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('hold', 'Hold'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hfghjgjvhj', to='transactions.project')),
            ],
        ),
    ]
