# Generated by Django 4.1.5 on 2024-09-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_project_working_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_working_order',
            name='rfid_value',
        ),
        migrations.AlterField(
            model_name='project_working_order',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
