# Generated by Django 4.1.5 on 2023-08-24 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_remove_scratch_stock_product_qr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_material',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_material_re_1', to='transactions.project'),
        ),
    ]
