# Generated by Django 4.1.5 on 2023-08-25 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_product_qr_moved_to_left_over'),
        ('transactions', '0026_alter_project_material_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_history',
            name='left_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fdsfcsfcscthfh', to='store.size'),
        ),
        migrations.AlterField(
            model_name='material_history',
            name='previous_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdsdsc', to='store.size'),
        ),
        migrations.AlterField(
            model_name='material_history',
            name='used_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fscswdcscdthfh', to='store.size'),
        ),
    ]
