# Generated by Django 4.1.5 on 2024-09-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_remove_project_working_order_rfid_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('hold', 'Hold'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10, null=True),
        ),
    ]
