# Generated by Django 4.1.5 on 2023-08-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0027_alter_material_history_left_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_matarial_qr',
            name='is_work_done',
            field=models.BooleanField(default=False),
        ),
    ]
