# Generated by Django 4.1.5 on 2024-09-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0028_alter_project_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_material',
            name='length',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project_material',
            name='width',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
