# Generated by Django 4.1.5 on 2023-08-30 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_item_code'),
        ('transactions', '0028_project_matarial_qr_is_work_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_matarial_qr',
            name='item_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_code_re_1', to='store.item_code'),
        ),
        migrations.AddField(
            model_name='project_matarial_qr',
            name='production_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
