# Generated by Django 4.1.5 on 2024-10-08 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0029_project_material_length_project_material_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_outward',
            name='date',
        ),
        migrations.RemoveField(
            model_name='project_outward',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project_outward',
            name='project',
        ),
        migrations.AddField(
            model_name='project_outward',
            name='project_matarial_production',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outward_item_code_barcode', to='transactions.project_matarial_production'),
            preserve_default=False,
        ),
    ]
