# Generated by Django 4.1.5 on 2024-10-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0030_remove_project_outward_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_matarial_production',
            name='barcode_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
