# Generated by Django 4.1.5 on 2023-08-31 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0030_remove_project_customer_project_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='customer_name',
            new_name='customer',
        ),
    ]
