# Generated by Django 4.1.5 on 2023-09-05 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_size_name'),
        ('transactions', '0032_project_matarial_qr_cutter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_matarial_qr',
            name='is_work_done',
        ),
        migrations.RemoveField(
            model_name='project_matarial_qr',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='project_matarial_qr',
            name='production_quantity',
        ),
        migrations.CreateModel(
            name='project_matarial_production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_quantity', models.IntegerField(blank=True, null=True)),
                ('item_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_code_re_1', to='store.item_code')),
                ('project_matarial_qr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_matarial_qr_production', to='transactions.project_matarial_qr')),
            ],
        ),
    ]
