# Generated by Django 4.1.5 on 2024-12-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0033_inward_item_code_inward_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward_supplier',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
