# Generated by Django 4.1.5 on 2023-09-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0034_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order_id',
            field=models.CharField(default='sdsd', max_length=50),
            preserve_default=False,
        ),
    ]
