# Generated by Django 4.1.5 on 2024-12-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0034_alter_inward_supplier_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward_supplier',
            name='item_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
