# Generated by Django 4.1.5 on 2023-09-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0035_project_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_material',
            name='sheet_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
