# Generated by Django 4.1.5 on 2024-12-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0035_alter_inward_supplier_item_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inward_supplier',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inward_supplier',
            name='item_code',
        ),
        migrations.AddField(
            model_name='inward_supplier',
            name='name',
            field=models.CharField(default='sasas', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inward_item_code',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inward_item_code',
            name='item_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
