# Generated by Django 4.1.5 on 2024-12-12 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0036_remove_inward_supplier_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_inward',
            name='inward_item_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transactions.inward_item_code'),
            preserve_default=False,
        ),
    ]
