# Generated by Django 4.1.5 on 2023-09-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0038_material_history_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='order_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
