# Generated by Django 4.1.5 on 2024-12-13 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_inward_supplier'),
        ('transactions', '0039_remove_project_inward_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_inward',
            name='inward_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.inward_supplier'),
        ),
        migrations.DeleteModel(
            name='inward_supplier',
        ),
    ]
