# Generated by Django 4.1.5 on 2023-09-19 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0039_alter_project_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_matarial_qr',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_instance_n', to='transactions.project'),
            preserve_default=False,
        ),
    ]
