# Generated by Django 4.1.5 on 2024-12-14 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0040_alter_project_inward_inward_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_matarial_production',
            name='main_label',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='project_outward_main_label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('project_matarial_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outward_item_code_main_label', to='transactions.project_matarial_production')),
            ],
        ),
    ]
