# Generated by Django 4.1.5 on 2023-09-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0040_project_matarial_qr_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_matarial_qr',
            name='project',
        ),
    ]
