# Generated by Django 4.1.5 on 2023-09-19 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_product_qr_finish'),
        ('transactions', '0041_remove_project_matarial_qr_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_history',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_n', to='store.size'),
            preserve_default=False,
        ),
    ]
