# Generated by Django 5.1.4 on 2024-12-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0041_project_matarial_production_main_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_outward_main_label',
            name='sr_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
