# Generated by Django 4.1.5 on 2023-09-19 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0042_material_history_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_history',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_n', to='transactions.project'),
        ),
    ]
