# Generated by Django 5.1.4 on 2024-12-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0043_project_outward_main_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_matarial_production',
            old_name='main_label',
            new_name='main_label_count',
        ),
    ]
