# Generated by Django 5.1.4 on 2024-12-22 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0044_rename_main_label_project_matarial_production_main_label_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_outward',
            name='main_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_label_re', to='transactions.project_outward_main_label'),
        ),
    ]
