# Generated by Django 5.1.4 on 2024-12-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0045_alter_project_outward_main_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_outward_main_label',
            name='sr_no',
        ),
    ]
