# Generated by Django 5.1.4 on 2025-01-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0046_remove_project_outward_main_label_sr_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order_child',
            name='order',
        ),
        migrations.DeleteModel(
            name='sales_customer',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='order_child',
        ),
    ]
