# Generated by Django 4.1.5 on 2023-09-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0046_remove_project_matarial_qr_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_matarial_production',
            name='project',
        ),
    ]
