# Generated by Django 4.1.5 on 2023-09-20 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0047_remove_project_matarial_production_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_matarial_production',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_production_n', to='transactions.project'),
            preserve_default=False,
        ),
    ]
