# Generated by Django 4.1.5 on 2023-09-26 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_size_mm1_size_mm2'),
        ('transactions', '0048_project_matarial_production_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_matarial_qr',
            name='cutter',
        ),
        migrations.AddField(
            model_name='material_history',
            name='cutter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.cutter'),
        ),
        migrations.AddField(
            model_name='project_matarial_qr',
            name='is_cutting_done',
            field=models.BooleanField(default=False),
        ),
    ]
