# Generated by Django 5.1.4 on 2025-01-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0048_project_inward_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_outward_main_label',
            name='invoice_no',
        ),
        migrations.AddField(
            model_name='project_matarial_production',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
