# Generated by Django 4.1.5 on 2023-10-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0049_remove_project_matarial_qr_cutter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_matarial_production',
            name='project_matarial_qr',
        ),
    ]
