# Generated by Django 5.1.4 on 2025-08-14 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0050_order_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order_booking',
        ),
    ]
