# Generated by Django 4.1.5 on 2023-10-15 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_employee_password'),
        ('transactions', '0050_remove_project_matarial_production_project_matarial_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='employee_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dfsdds', to='store.employee'),
        ),
    ]
