# Generated by Django 4.1.5 on 2023-10-21 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0051_alter_project_employee_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_logs', to='transactions.project')),
            ],
        ),
    ]
