# Generated by Django 5.1.4 on 2025-08-20 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_booking', '0013_alter_production_orders_stage'),
        ('transactions', '0051_delete_order_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_working_order',
            name='project',
        ),
        migrations.AddField(
            model_name='project_working_order',
            name='order_booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hfghjgjvhj', to='order_booking.order_booking'),
            preserve_default=False,
        ),
    ]
