# Generated by Django 5.1.4 on 2025-11-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0052_remove_project_working_order_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='system_alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reception', 'Reception'), ('designer', 'Designer'), ('production', 'Production')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
