# Generated by Django 4.1.5 on 2023-10-21 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0053_project_logs_field_name_project_logs_new_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_logs',
            name='description',
        ),
        migrations.CreateModel(
            name='project_sheets_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdcdcsx', to='transactions.project')),
            ],
        ),
    ]
