# Generated by Django 4.1.5 on 2023-12-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0055_notification_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_table',
            name='is_read',
            field=models.BooleanField(default=True),
        ),
    ]
