# Generated by Django 4.1.5 on 2023-12-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0056_notification_table_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_table',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
