# Generated by Django 4.1.5 on 2023-12-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0057_alter_notification_table_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification_table',
            name='is_read',
        ),
        migrations.AddField(
            model_name='notification_table',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
    ]
