# Generated by Django 4.1.5 on 2023-12-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0058_remove_notification_table_is_read_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('urgency', models.TextField()),
                ('requirements', models.TextField()),
                ('invoice', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_reported', models.BooleanField(default=False)),
            ],
        ),
    ]
