# Generated by Django 4.1.5 on 2023-12-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0059_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.TextField(default='abcd'),
            preserve_default=False,
        ),
    ]
