# Generated by Django 4.1.5 on 2024-02-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0061_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desgin_file',
            field=models.FileField(default=1, upload_to='media/project_design/'),
            preserve_default=False,
        ),
    ]
