# Generated by Django 4.1.5 on 2024-02-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0065_values_for_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='sheets_rifd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=50)),
                ('sheet_id', models.CharField(max_length=50, unique=True)),
                ('rfid_value', models.CharField(max_length=50, unique=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='values_for_assignment',
            name='completed',
        ),
    ]
