# Generated by Django 4.1.5 on 2024-02-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0067_alter_values_for_assignment_sheet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='sheet_tracking_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=50)),
                ('sheet_id', models.CharField(max_length=50)),
                ('rfid_value', models.CharField(max_length=50)),
                ('check_point', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='values_for_assignment',
        ),
        migrations.RemoveField(
            model_name='sheets_rifd',
            name='completed',
        ),
        migrations.AddField(
            model_name='sheets_rifd',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sheets_rifd',
            name='rfid_value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sheets_rifd',
            name='sheet_id',
            field=models.CharField(max_length=50),
        ),
    ]
