# Generated by Django 4.1.5 on 2024-02-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0068_sheet_tracking_history_delete_values_for_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='design_file',
        ),
        migrations.RemoveField(
            model_name='project',
            name='own_design_file',
        ),
    ]
