# Generated by Django 4.1.5 on 2024-03-23 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0069_remove_project_design_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_reported',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='urgency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='order_child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.TextField()),
                ('material', models.CharField(choices=[('ss_304', 'ss_304'), ('ss_316', 'ss_316'), ('ss_316_L', 'ss_316_L'), ('aluminium_coil', 'aluminium_coil'), ('sheet_2S', 'sheet_2S'), ('brass', 'brass'), ('copper', 'copper'), ('mild_sheel', 'mild_sheel'), ('spring_sheel', 'spring_sheel'), ('nickel', 'nickel'), ('beryllium_copper', 'beryllium_copper'), ('trifoliate_sandwich', 'trifoliate_sandwich'), ('any_other_please_mention', 'any_other_please_mention')], max_length=50)),
                ('process', models.CharField(choices=[('chemical_etching', 'chemical_etching'), ('etching_laser_cutting', 'etching_laser_cutting'), ('etching_laser_engraving', 'etching_laser_engraving'), ('chemical_milling', 'chemical_milling'), ('anodic_print', 'anodic_print'), ('laser_cutting', 'laser_cutting'), ('laser_cutting_coating', 'laser_cutting_coating'), ('stamping', 'stamping'), ('injection_mould_texturing', 'injection_mould_texturing')], max_length=50)),
                ('sqinch', models.CharField(choices=[('144', '144'), ('288', '288'), ('432', '432'), ('576', '576'), ('720', '720'), ('864', '864'), ('1008', '1008'), ('1152', '1152'), ('1296', '1296'), ('1440', '1440'), ('1584', '1584'), ('1728', '1728'), ('1872', '1872'), ('2016', '2016'), ('2160', '2160'), ('2304', '2304'), ('2448', '2448'), ('2592', '2592'), ('2736', '2736'), ('2880', '2880'), ('3024', '3024'), ('3168', '3168'), ('3312', '3312'), ('3456', '3456'), ('3600', '3600'), ('3744', '3744'), ('3888', '3888'), ('4032', '4032'), ('4176', '4176'), ('4320', '4320'), ('4464', '4464'), ('4608', '4608')], max_length=50)),
                ('text_matter', models.CharField(choices=[('standard_text_matter', 'standard_text_matter'), ('variable_text_matter', 'variable_text_matter')], max_length=50)),
                ('etching', models.CharField(choices=[('deep_etching', 'deep_etching'), ('embossed_etching', 'embossed_etching')], max_length=50)),
                ('color_count', models.CharField(choices=[('1', '1'), ('2', '2'), ('multi_color', 'multi_color')], max_length=50)),
                ('color', models.CharField(choices=[('1', '1'), ('2', '2'), ('multi_color', 'multi_color')], max_length=50)),
                ('font_height', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('above_8', 'above_8'), ('combination_of_1to8', 'combination_of_1to8')], max_length=50)),
                ('thickness', models.CharField(choices=[('0.1', '0.1'), ('0.2', '0.2'), ('0.3', '0.3'), ('0.4', '0.4'), ('0.5', '0.5'), ('0.6', '0.6'), ('0.7', '0.7'), ('0.8', '0.8'), ('0.9', '0.9'), ('1.0', '1.0'), ('1.2', '1.2'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3.0', '3.0')], max_length=50)),
                ('total_sqinch', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('rate_per_unit', models.IntegerField()),
                ('basoc_amount', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fdthfh', to='transactions.order')),
            ],
        ),
    ]
