# Generated by Django 4.1.5 on 2024-03-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0070_remove_order_is_reported_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_child',
            name='basoc_amount',
        ),
        migrations.RemoveField(
            model_name='order_child',
            name='sqinch',
        ),
        migrations.RemoveField(
            model_name='order_child',
            name='total_sqinch',
        ),
        migrations.AddField(
            model_name='order_child',
            name='basic_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_child',
            name='total_sq_inch',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_child',
            name='color',
            field=models.CharField(choices=[('black', 'black'), ('blue', 'blue'), ('red', 'red'), ('green', 'green'), ('yellow', 'yellow')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order_child',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order_child',
            name='rate_per_unit',
            field=models.FloatField(),
        ),
    ]
