# Generated by Django 4.1.5 on 2024-03-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0071_remove_order_child_basoc_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
