# Generated by Django 4.1.5 on 2024-04-20 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0072_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_child',
            name='order',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='order_child',
        ),
    ]
