# Generated by Django 4.1.5 on 2024-04-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0074_order_order_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_child',
            name='basic_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_child',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_child',
            name='rate_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_child',
            name='total_amount_with_charges_type',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_child',
            name='total_sq_inch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_child',
            name='total_with_gst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_child',
            name='total_with_job_shop',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
