# Generated by Django 4.1.5 on 2024-04-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0075_alter_order_child_basic_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_child',
            name='flim_charges_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_child',
            name='flim_sqinch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order_child',
            name='flim_charges',
            field=models.CharField(choices=[('inclusive', 'inclusive'), ('sqinch', 'sqinch')], max_length=50),
        ),
    ]
