# Generated by Django 4.1.5 on 2024-04-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0076_order_child_flim_charges_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='month_procurement',
        ),
        migrations.AlterField(
            model_name='order',
            name='credit_in_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
