# Generated by Django 4.1.5 on 2024-04-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0077_remove_order_month_procurement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='advance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
