# Generated by Django 4.1.5 on 2024-04-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0078_remove_order_order_id_alter_order_advance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final_amount',
            field=models.FloatField(),
        ),
    ]
