# Generated by Django 4.1.5 on 2024-04-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0079_alter_order_final_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_child',
            name='sample',
            field=models.CharField(choices=[('Free_in_case_confirm_Order', 'Free_in_case_confirm_Order'), ('Extra_Charges_Rs', 'Extra_Charges_Rs')], default='Free_in_case_confirm_Order', max_length=50),
            preserve_default=False,
        ),
    ]
