# Generated by Django 4.1.5 on 2024-04-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0080_order_child_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_child',
            name='sample_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
