# Generated by Django 4.1.5 on 2024-04-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0081_order_child_sample_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_child',
            name='certificate_cost',
            field=models.CharField(choices=[('Free_along_with_invoice', 'Free_along_with_invoice'), ('No_certification', 'No_certification')], default='Free_along_with_invoice', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_child',
            name='certificate_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
