# Generated by Django 4.1.5 on 2024-04-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0082_order_child_certificate_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='client_gst',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='description',
            new_name='contact_no',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='requirements',
            new_name='contance_person_no',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='urgency',
            new_name='customer_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='invoice',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
