# Generated by Django 4.1.5 on 2024-04-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0083_rename_customer_order_client_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference_from',
            field=models.CharField(choices=[('Direct_Contact', 'Direct_Contact'), ('Webiste', 'Webiste'), ('Mailer', 'Mailer')], default='Mailer', max_length=100),
            preserve_default=False,
        ),
    ]
