# Generated by Django 4.1.5 on 2024-04-25 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_product_qr_status'),
        ('transactions', '0084_order_reference_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='sudden_rise_percent',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_child',
            name='certificate_cost',
            field=models.CharField(choices=[('Free_along_with_invoice', 'Free_along_with_invoice'), ('No_certification', 'No_certification'), ('Extra_Charges', 'Extra_Charges')], max_length=50),
        ),
    ]
