# Generated by Django 4.1.5 on 2024-04-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0085_remove_order_customer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales_customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('mobile_no', models.IntegerField()),
                ('client_gst', models.CharField(max_length=120)),
            ],
        ),
    ]
