# Generated by Django 4.1.5 on 2024-04-26 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0085_remove_order_customer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales_customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('mobile_no', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.sales_customer'),
        ),
    ]
