# Generated by Django 4.1.5 on 2024-04-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0087_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_gst',
        ),
        migrations.AddField(
            model_name='order_child',
            name='final_item_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
