# Generated by Django 4.1.5 on 2024-04-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0091_order_total_sqinch'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_child',
            name='other_material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
